#!/bin/bash
# SignalK Server - Complete Security Test Runner
# Runs all security tests and generates consolidated report

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPORTS_DIR="$SCRIPT_DIR/reports"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         SignalK Server - Security Test Suite                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Timestamp: $TIMESTAMP"
echo "Project: $PROJECT_ROOT"
echo ""

mkdir -p "$REPORTS_DIR"

# Initialize report
REPORT_FILE="$REPORTS_DIR/security-report-$TIMESTAMP.md"
cat > "$REPORT_FILE" << EOF
# SignalK Server Security Test Report

**Date:** $(date)
**Server Version:** $(node -p "require('$PROJECT_ROOT/package.json').version" 2>/dev/null || echo "unknown")

---

EOF

# Track overall status
OVERALL_STATUS=0

# Function to run a test phase
run_phase() {
    local phase_name="$1"
    local phase_script="$2"
    local phase_status=0

    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}Running: $phase_name${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    echo "" >> "$REPORT_FILE"
    echo "## $phase_name" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"

    if eval "$phase_script" >> "$REPORTS_DIR/${phase_name// /-}-$TIMESTAMP.log" 2>&1; then
        echo -e "${GREEN}✓ $phase_name completed successfully${NC}"
        echo "**Status:** ✅ Passed" >> "$REPORT_FILE"
    else
        echo -e "${RED}✗ $phase_name had issues (see log)${NC}"
        echo "**Status:** ⚠️ Issues Found" >> "$REPORT_FILE"
        phase_status=1
        OVERALL_STATUS=1
    fi

    echo "**Log:** \`reports/${phase_name// /-}-$TIMESTAMP.log\`" >> "$REPORT_FILE"
    echo ""
}

# 1. Dependency Scanning
run_phase "Dependency Scan" "cd '$PROJECT_ROOT' && npm audit --production 2>&1; snyk test 2>&1 || true"

# 2. Static Analysis
run_phase "Static Analysis" "cd '$PROJECT_ROOT' && semgrep --config=p/nodejs --json 2>&1 || echo 'Semgrep not installed'"

# 3. Secrets Scan
run_phase "Secrets Scan" "cd '$PROJECT_ROOT' && gitleaks detect --source . 2>&1 || echo 'Gitleaks not installed'"

# 4. Security Tests (if server is running)
echo -e "${YELLOW}Checking if SignalK server is running...${NC}"
if curl -s http://localhost:3000/signalk > /dev/null 2>&1; then
    echo -e "${GREEN}Server detected at localhost:3000${NC}"

    run_phase "WebSocket Security Tests" "cd '$PROJECT_ROOT' && npx mocha 'security-testing/tests/websocket/*.test.js' --timeout 30000 2>&1"
    run_phase "Authentication Tests" "cd '$PROJECT_ROOT' && npx mocha 'security-testing/tests/auth/*.test.js' --timeout 30000 2>&1"
    run_phase "ACL Security Tests" "cd '$PROJECT_ROOT' && npx mocha 'security-testing/tests/acl/*.test.js' --timeout 30000 2>&1"
    run_phase "API Security Tests" "cd '$PROJECT_ROOT' && npx mocha 'security-testing/tests/api/*.test.js' --timeout 30000 2>&1"
    run_phase "Fuzzing Tests" "cd '$PROJECT_ROOT' && npx mocha 'security-testing/tests/fuzzing/*.test.js' --timeout 60000 2>&1"
else
    echo -e "${YELLOW}Server not running. Skipping runtime tests.${NC}"
    echo "Start the server with: npm start"
    echo ""
    echo "## Runtime Tests" >> "$REPORT_FILE"
    echo "**Status:** ⏭️ Skipped (server not running)" >> "$REPORT_FILE"
fi

# Generate summary
echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "## Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
if [ $OVERALL_STATUS -eq 0 ]; then
    echo "**Overall Status:** ✅ All tests passed" >> "$REPORT_FILE"
else
    echo "**Overall Status:** ⚠️ Some issues found - review logs" >> "$REPORT_FILE"
fi
echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Report generated by SignalK Security Testing Framework*" >> "$REPORT_FILE"

# Final output
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                      Test Complete                             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Reports saved to: $REPORTS_DIR/"
echo "Main report: $REPORT_FILE"
echo ""

if [ $OVERALL_STATUS -eq 0 ]; then
    echo -e "${GREEN}All security tests passed!${NC}"
else
    echo -e "${YELLOW}Some issues were found. Review the reports for details.${NC}"
fi

exit $OVERALL_STATUS
